### ISSUE TITLE
default shortcut for open project is overwritten

### ISSUE THREAD

**Issue by Thormill** [webArtisan/lessTabs#3]
hi!
firstly, thx a log for a plugin.
secondly, i found that with this plugin default shortcut for quick open project (cntrl+alt+p) is closing tabs, not opening project window.
i tried to re-assign shortcut for opening project, but, unfortunatelly, i failed.
i'd suggest you to use not binded by default shortcuts, or please let me know how to re-assign your command, binded to cntrl-alt-p

**Comment by Thormill** [comment]
oh, forgot to tell, i'm using Linux Kubuntu 13.04 x64

**Comment by Thormill** [comment]
i've found key bindings in settings, sorry for my bad attention.
i remapped "cntrl+alt+u+p", but still have issue. when less_tabs is disabled in package controle, it works as it should

**Comment by webArtisan** [comment]
Hello,
I'm happy that you liked the plugin.
You can find the default shortcut key bindings by opening the menu 
"Preferences -> Package Settings -> lessTabs -> Key Bindings - Default".

This will open automatically the key binding for you OS.
The default shortcut for closing unrelated tabs for current project is "ctrl + alt + u + p" and not "ctrl + alt + p", this probably a sublime bug, not showing the "u" key.

In order to change a key binding
First you copy the line of the command that you want to change it's key binding and the you paste in the file of custom bindings.
You open the custom key binding file from :
"Preferences -> Package Settings -> lessTabs -> Key Bindings - User"
OR
"Preferences -> Key Bindings - User"
Once you pasted it, you change the "keys" value in our example "ctrl+alt+u+p" to what ever you like.

About disabling the package, this not something that i can control or override.
To make sure that the plugin is disabled you need to find "Less Tabs" in "ignored_packages" in "Preferences -> Settings - User"

**Comment by niosus** [comment]
I would argue this issue is still not closed. The default key bindings are: `"keys": ["ctrl+alt+u+p"], "command": "less_tabs_close_project_unrelated"`. However, when I press <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>p</kbd> to switch the project it closes all my tabs. I am on Ubuntu 14.04 and latest Sublime Text 3. 

Would you maybe consider changing default keybindings to something else?
